import datetime
from sqlalchemy.orm import Session
from app import models, schemas, crud

def recalculate_risk(db: Session, site_id: str):
    site = crud.get_site(db, site_id)
    if not site:
        return

    # Get latest data
    rain = crud.get_rainfall_observations(db, site_id, limit=1)
    water = crud.get_water_level_observations(db, site_id, limit=1)
    det = crud.get_detections(db, site_id, limit=1)

    latest_rain = rain[0].rainfall_24h_mm if rain else 0
    latest_water = water[0].water_depth_m if water else 1.0
    latest_det_kg = det[0].estimated_surface_mass_kg if det else 0

    # Rule-based scoring
    # Base risk
    risk = 20.0

    # Water level contribution (assume 1.5m is high, 2.5m is critical)
    if latest_water > 2.0:
        risk += 35
    elif latest_water > 1.5:
        risk += 20
    elif latest_water > 1.0:
        risk += 10

    # Rainfall contribution
    if latest_rain > 50:
        risk += 20
    elif latest_rain > 20:
        risk += 10

    # Plastic accumulation contribution (kg)
    if latest_det_kg > 500:
        risk += 25
    elif latest_det_kg > 200:
        risk += 15

    risk = min(100.0, risk)

    # Determine level
    level = "Low"
    if risk >= 75:
        level = "Critical"
    elif risk >= 60:
        level = "High"
    elif risk >= 40:
        level = "Medium"

    # Update site
    crud.update_site(db, site_id, schemas.MonitoringSiteUpdate(
        current_risk_score=risk,
        current_risk_level=level
    ))

    # If high risk, create a cleanup task if one doesn't exist
    if level in ["High", "Critical"]:
        # check if pending task exists
        tasks = crud.get_cleanup_tasks(db, status="Pending", site_id=site_id)
        if not tasks:
            crud.create_cleanup_task(db, schemas.CleanupTaskCreate(
                site_id=site_id,
                title=f"Emergency Choke Clearance - {site.name}",
                priority=level,
                team_name="Quick Response Team A",
                target_date=datetime.datetime.utcnow().strftime("%Y-%m-%d"),
                estimated_load_kg=latest_det_kg,
                notes="Auto-generated by IoT Risk Engine due to high water level and plastic accumulation."
            ))

def process_iot_payload(db: Session, payload: schemas.IoTSensorPayload) -> dict:
    device = crud.get_device(db, payload.device_id)
    if not device:
        # Create it if it doesn't exist
        # We need a site_id, let's extract it from device_id, e.g., "ESP32-MTH-01" -> "MTH-01"
        site_id = payload.device_id.replace("ESP32-", "")
        # Verify site exists
        site = crud.get_site(db, site_id)
        if not site:
            raise ValueError(f"Unknown site ID derived from device: {site_id}")
        
        device = crud.create_device(db, schemas.IoTDeviceCreate(
            id=payload.device_id,
            site_id=site_id,
            is_simulated=False,
            status="Online",
            battery_level=payload.battery_level,
            signal_strength=payload.signal_strength
        ))
    
    # Update device status
    crud.update_device(db, device.id, schemas.IoTDeviceUpdate(
        status="Online",
        last_seen=payload.timestamp,
        battery_level=payload.battery_level,
        signal_strength=payload.signal_strength
    ))

    # Insert Water Level
    crud.create_water_level_observation(db, schemas.WaterLevelObservationCreate(
        site_id=device.site_id,
        water_depth_m=payload.water_level_cm / 100.0,
        flow_velocity_mps=0.5, # Default
        source_status="Real" if not device.is_simulated else "Simulated"
    ))

    # Insert Rainfall if present
    if payload.rainfall_mm is not None:
        crud.create_rainfall_observation(db, schemas.RainfallObservationCreate(
            site_id=device.site_id,
            rainfall_1h_mm=payload.rainfall_mm,
            rainfall_24h_mm=payload.rainfall_mm * 2, # Rough estimate
            forecast_24h_mm=0.0,
            sensor_id=device.id,
            source_status="Real" if not device.is_simulated else "Simulated"
        ))
    
    # Insert Plastic Detection if present
    if payload.plastic_detection:
        # Map string to kg
        mass = 100.0
        if payload.plastic_detection == "High":
            mass = 800.0
        elif payload.plastic_detection == "Medium":
            mass = 300.0
        elif payload.plastic_detection == "Low":
            mass = 50.0

        crud.create_detection(db, schemas.PlasticDetectionCreate(
            site_id=device.site_id,
            image_path="/api/static/sample_feeds/camera1.jpg",
            total_objects_detected=int(mass / 2),
            estimated_surface_mass_kg=mass,
            source_status="Real" if not device.is_simulated else "Simulated"
        ))

    # Recalculate Risk
    recalculate_risk(db, device.site_id)

    return {"status": "success", "device_id": device.id}
